### PR TITLE
Release/v0.38.0

### PR DESCRIPTION
**Pull request by venkatamutyala**
## **Type**
enhancement

___

## **Description**
- Updated Chart version to 0.38.0 and README version badge to 0.38.0-rc3.
- Multiple application chart versions and image tags updated for enhancements, including:
  - Backup tools, External-DNS, External-Secrets, Operator WAF and its Web ACL, Kube-Prometheus-Stack, Loki, Nginx, Promtail, Pull-Request-Bot, QR Code Generator, Strimzi, Vault Init Controller, and Vault.
- Specifically for Kube-Prometheus-Stack, disabled leaked secrets enforcement for Grafana.
- Added image tag configuration for Nginx controller to "v1.9.6".

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes
</strong></td><td><details><summary>1 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>Chart.yaml</strong><dd><code>Update Chart Version to 0.38.0</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
Chart.yaml

- Version updated from 0.37.1 to 0.38.0.

</details>
    

  </td>
  <td><a href="https:/GlueOps/platform-helm-chart-platform/pull/175/files#diff-d954583aa4c24cff0039bc948abd7c694fc3dab2030231d11ed1b3cda9b4ddbe">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></details></td></tr><tr><td><strong>Documentation
</strong></td><td><details><summary>1 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>README.md</strong><dd><code>Update README Version Badge to 0.38.0-rc3</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
README.md

- Version badge updated to 0.38.0-rc3.

</details>
    

  </td>
  <td><a href="https:/GlueOps/platform-helm-chart-platform/pull/175/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></details></td></tr><tr><td><strong>Enhancement
</strong></td><td><details><summary>17 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>application-backups-and-exports.yaml</strong><dd><code>Update Backup Tools Image Version</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
templates/application-backups-and-exports.yaml

- Updated `backup-tools` image version from v0.9.2 to v0.9.4.

</details>
    

  </td>
  <td><a href="https:/GlueOps/platform-helm-chart-platform/pull/175/files#diff-b8741a1ff9ee30514ce50acd27aaab4531d5402c104bf8d28e0404d9b1f43a8c">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>application-external-dns.yaml</strong><dd><code>Update External-DNS Chart Version</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
templates/application-external-dns.yaml

- Updated `external-dns` targetRevision from 6.28.1 to 6.32.1.

</details>
    

  </td>
  <td><a href="https:/GlueOps/platform-helm-chart-platform/pull/175/files#diff-77f505fbaa80b2ae0f9386fda952a8ed063fc00d35b729f2f24a66b1070900f6">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>application-external-secrets-crd.yaml</strong><dd><code>Update External-Secrets CRDs Version</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
templates/application-external-secrets-crd.yaml

- Updated path for external-secrets CRDs from v0.9.11 to v0.9.12.

</details>
    

  </td>
  <td><a href="https:/GlueOps/platform-helm-chart-platform/pull/175/files#diff-44e8fdb9956be0b83b3163f6d4de48a0b16d24110cea9a0beb60736af1b2ec66">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>application-external-secrets.yaml</strong><dd><code>Update External-Secrets Chart Version</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
templates/application-external-secrets.yaml

<li>Updated <code>glueops-external-secrets</code> targetRevision from 0.5.6 to 0.5.7.<br>

</details>
    

  </td>
  <td><a href="https:/GlueOps/platform-helm-chart-platform/pull/175/files#diff-598d87689ac37c6848a972300a5dabece11e08c1b1b32f51360ec310cb8d7e6b">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>application-glueops-operator-waf-web-acl.yaml</strong><dd><code>Update Operator WAF Web ACL Image Version</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
templates/application-glueops-operator-waf-web-acl.yaml

- Updated image tag from v0.3.0 to v0.3.1.

</details>
    

  </td>
  <td><a href="https:/GlueOps/platform-helm-chart-platform/pull/175/files#diff-b045d28424e2562cc1b7b1e8f9536f322332a30a3002ee6b9443f21f1bf6f472">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>application-glueops-operator-waf.yaml</strong><dd><code>Update Operator WAF Image Version</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
templates/application-glueops-operator-waf.yaml

- Updated image tag from v0.5.0 to v0.5.1.

</details>
    

  </td>
  <td><a href="https:/GlueOps/platform-helm-chart-platform/pull/175/files#diff-59f2d123d85fdcee1a6d3a2997e19b7c22fb699a41e0334acba55bcdf20185a2">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>application-kube-prometheus-stack-crds.yaml</strong><dd><code>Update Kube-Prometheus-Stack CRDs Version</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
templates/application-kube-prometheus-stack-crds.yaml

<li>Updated targetRevision for kube-prometheus-stack CRDs from 55.7.0 to <br>56.6.2.<br>

</details>
    

  </td>
  <td><a href="https:/GlueOps/platform-helm-chart-platform/pull/175/files#diff-fa78af7b7e24b6b39d9c41631e83a6fdd691fd36c357a04279d083356459c28d">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>application-kube-prometheus-stack.yaml</strong><dd><code>Update Kube-Prometheus-Stack Chart and Grafana Configuration</code></dd></summary>
<hr>
      
templates/application-kube-prometheus-stack.yaml

<li>Updated kube-prometheus-stack chart version from 55.7.0 to 56.6.2.<br> <li> Disabled leaked secrets enforcement for Grafana.<br>

</details>
    

  </td>
  <td><a href="https:/GlueOps/platform-helm-chart-platform/pull/175/files#diff-87a59bc30480a9bd9c023721224637a3e2c117ea1b0a2843f98188bc105f3ce3">+3/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>application-loki-alert-group-controller.yaml</strong><dd><code>Update Loki Alert Group Controller Image Version</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
templates/application-loki-alert-group-controller.yaml

- Updated image tag from v0.2.7 to v0.2.8.

</details>
    

  </td>
  <td><a href="https:/GlueOps/platform-helm-chart-platform/pull/175/files#diff-09fc427726cfb518f847f06ab0888b91dc9ed880eb3455c69e7de0e08f4e44ee">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>application-loki.yaml</strong><dd><code>Update Loki Chart Version</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
templates/application-loki.yaml

- Updated Loki chart version from 5.41.4 to 5.42.2.

</details>
    

  </td>
  <td><a href="https:/GlueOps/platform-helm-chart-platform/pull/175/files#diff-35d196c1e2f73b4c5bae7a929e46ae128a109d728fe4b5fa588e5ebd1853134b">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>application-nginx-public.yaml</strong><dd><code>Configure Nginx Controller Image Version</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
templates/application-nginx-public.yaml

- Added image tag configuration for nginx controller to "v1.9.6".

</details>
    

  </td>
  <td><a href="https:/GlueOps/platform-helm-chart-platform/pull/175/files#diff-b8951700ccd41112fa2d2a037fe78e1b4f6e49da48fc3592c0605afdad3c15cc">+2/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>application-promtail.yaml</strong><dd><code>Update Promtail Image Version</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
templates/application-promtail.yaml

- Updated Promtail image tag from 2.9.3 to 2.9.4.

</details>
    

  </td>
  <td><a href="https:/GlueOps/platform-helm-chart-platform/pull/175/files#diff-9214e9cc299a32be849e6e9b3d1ade7f937a12b1b06d6be9327ef03dfd9438e4">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>application-pull-request-bot.yaml</strong><dd><code>Update Pull-Request-Bot Image Version</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
templates/application-pull-request-bot.yaml

- Updated pull-request-bot image tag from v0.12.1 to v0.12.2.

</details>
    

  </td>
  <td><a href="https:/GlueOps/platform-helm-chart-platform/pull/175/files#diff-7e4edd3e2254c967df8fa1e2864df1fc07fe03327efbe1fb36e92bd332ae6f8a">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>application-qr-code-generator.yaml</strong><dd><code>Update QR Code Generator Image Version</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
templates/application-qr-code-generator.yaml

- Updated QR Code Generator image tag from v0.2.9 to v0.2.10.

</details>
    

  </td>
  <td><a href="https:/GlueOps/platform-helm-chart-platform/pull/175/files#diff-78cf2195e956cb1d4d7052085ba03b1923bfef65ef547778ded8805bb31d0199">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>application-strimzi.yaml</strong><dd><code>Update Strimzi Chart Version</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
templates/application-strimzi.yaml

- Updated Strimzi chart version from 0.37.0 to 0.39.0.

</details>
    

  </td>
  <td><a href="https:/GlueOps/platform-helm-chart-platform/pull/175/files#diff-b4950f359a8628d61320ce52771321218acd077d8436724d28140a8ab91ae05c">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>application-vault-init-controller.yaml</strong><dd><code>Update Vault Init Controller Image Version</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
templates/application-vault-init-controller.yaml

- Updated image tag from v0.2.2 to v0.2.3.

</details>
    

  </td>
  <td><a href="https:/GlueOps/platform-helm-chart-platform/pull/175/files#diff-42aebb2879ee0b37491aae9be9f84965f0c3c50e5872eeae3bc901cc28e13a2c">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>application-vault.yaml</strong><dd><code>Update Vault Image Version</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
templates/application-vault.yaml

- Updated Vault image tag from 1.14.8 to 1.14.9.

</details>
    

  </td>
  <td><a href="https:/GlueOps/platform-helm-chart-platform/pull/175/files#diff-cb4686972e88e1c744b094bfe3d13b6e64bf2a5b0a9bd9a69a7f187f4f387642">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></details></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by venkatamutyala** [comment]
/ask give me a summary of all the changes in this PR

**Comment by venkatamutyala** [comment]
/ask can you give me a short and sweet summary in the PR description versus a fancy table.

**Review by fernandoataoldotcom — APPROVED** [review]

**Pull request merged**
